builds:
-
  id: kata02
  binary: kata02
  main: ./cmd/kata02
  env:
    - CGO_ENABLED=0
-
  id: kata19
  binary: kata19
  main: ./cmd/kata19
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - github:
      owner: arvenil
      name: homebrew-kata
    homepage: "https://github.com/arvenil/kata"
    description: "Kata 形🤺 exercises"
    folder: Formula
    test: |
      system "#{bin}/kata02 -h"
      system "#{bin}/kata19 -h"
