builds:
-
  id: bsearch
  binary: bsearch
  main: ./cmd/bsearch
  env:
    - CGO_ENABLED=0
-
  id: ladder
  binary: ladder
  main: ./cmd/ladder
  env:
    - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: arvenil
      name: homebrew-kata
    homepage: "https://github.com/arvenil/kata"
    description: "Kata 形🤺 exercises"
    folder: Formula
    test: |
      system "#{bin}/bsearch -h"
      system "#{bin}/ladder -h"
signs:
  - artifacts: all
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
