name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build ./...

    - name: Install
      run: go install -v ./...

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v1
