name: go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install word list
      run: sudo apt-get install wamerican

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build ./...

    - name: Install
      run: go install -v ./...

    - name: Test
      run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v1

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.txt
        outfile: coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
